# Generated by Django 3.2.4 on 2021-06-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imggal',
            name='image',
            field=models.ImageField(upload_to='media/static/images/'),
        ),
    ]
